import { Tool } from "@/types/tools";

export const developerTools: Tool[] = [
  {
    icon: "FileJson",
    label: "toolsList.dev.jsonFormatter.label",
    description: "toolsList.dev.jsonFormatter.description",
    href: "/dev-tools/json-formatter",
    badge: "common.popular",
    badgeColor: "bg-emerald-100 text-emerald-600",
  },
  {
    icon: "Binary",
    label: "toolsList.dev.base64.label",
    description: "toolsList.dev.base64.description",
    href: "/dev-tools/base64-encoder",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Terminal",
    label: "toolsList.dev.regex.label",
    description: "toolsList.dev.regex.description",
    href: "/dev-tools/regex-tester",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Hash",
    label: "toolsList.dev.uuid.label",
    description: "toolsList.dev.uuid.description",
    href: "/dev-tools/uuid-generator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Code2",
    label: "toolsList.dev.htmlFormatter.label",
    description: "toolsList.dev.htmlFormatter.description",
    href: "/dev-tools/html-formatter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Braces",
    label: "toolsList.dev.cssFormatter.label",
    description: "toolsList.dev.cssFormatter.description",
    href: "/dev-tools/css-formatter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Link",
    label: "toolsList.dev.urlEncoder.label",
    description: "toolsList.dev.urlEncoder.description",
    href: "/dev-tools/url-encoder",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Clock",
    label: "toolsList.dev.timestamp.label",
    description: "toolsList.dev.timestamp.description",
    href: "/dev-tools/unix-timestamp",
    badge: "common.new",
    badgeColor: "bg-emerald-100 text-emerald-600",
  },
  {
    icon: "Shuffle",
    label: "toolsList.dev.jwt.label",
    description: "toolsList.dev.jwt.description",
    href: "/dev-tools/jwt-decoder",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "AlignLeft",
    label: "toolsList.dev.markdownToHtml.label",
    description: "toolsList.dev.markdownToHtml.description",
    href: "/dev-tools/markdown-html",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Table",
    label: "toolsList.dev.csvToJson.label",
    description: "toolsList.dev.csvToJson.description",
    href: "/dev-tools/csv-to-json",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "GitCompare",
    label: "toolsList.dev.jsonDiff.label",
    description: "toolsList.dev.jsonDiff.description",
    href: "/dev-tools/json-diff",
    badge: null,
    badgeColor: "",
  },
];
