import { Tool } from "@/types/tools";

export const imageTools: Tool[] = [
  {
    icon: "Crop",
    label: "toolsList.image.resizer.label",
    description: "toolsList.image.resizer.description",
    href: "/image-tools/resizer",
    badge: "common.popular",
    badgeColor: "bg-violet-100 text-violet-600",
  },
  {
    icon: "Minimize2",
    label: "toolsList.image.compressor.label",
    description: "toolsList.image.compressor.description",
    href: "/image-tools/compressor",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "ImagePlus",
    label: "toolsList.image.converter.label",
    description: "toolsList.image.converter.description",
    href: "/image-tools/format-converter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Palette",
    label: "toolsList.image.colorPicker.label",
    description: "toolsList.image.colorPicker.description",
    href: "/image-tools/color-picker",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "FlipHorizontal",
    label: "toolsList.image.flipper.label",
    description: "toolsList.image.flipper.description",
    href: "/image-tools/flipper",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "RotateCw",
    label: "toolsList.image.rotator.label",
    description: "toolsList.image.rotator.description",
    href: "/image-tools/rotator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "ScanLine",
    label: "toolsList.image.toBase64.label",
    description: "toolsList.image.toBase64.description",
    href: "/image-tools/base64bit",
    badge: "common.new",
    badgeColor: "bg-emerald-100 text-emerald-600",
  },
  {
    icon: "Contrast",
    label: "toolsList.image.grayscale.label",
    description: "toolsList.image.grayscale.description",
    href: "/image-tools/grayscale-converter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Frame",
    label: "toolsList.image.watermark.label",
    description: "toolsList.image.watermark.description",
    href: "/image-tools/watermark",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Layers",
    label: "toolsList.image.merger.label",
    description: "toolsList.image.merger.description",
    href: "/image-tools/merger",
    badge: null,
    badgeColor: "",
  },
];
