import { Tool } from "@/types/tools";

export const pdfTools: Tool[] = [
  {
    icon: "FilePlus2",
    label: "toolsList.pdf.merger.label",
    description: "toolsList.pdf.merger.description",
    href: "/pdf-tools/merger",
    badge: "common.popular",
    badgeColor: "bg-rose-100 text-rose-600",
  },
  {
    icon: "Scissors",
    label: "toolsList.pdf.splitter.label",
    description: "toolsList.pdf.splitter.description",
    href: "/pdf-tools/splitter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Minimize2",
    label: "toolsList.pdf.compressor.label",
    description: "toolsList.pdf.compressor.description",
    href: "/pdf-tools/compressor",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "FileOutput",
    label: "toolsList.pdf.toWord.label",
    description: "toolsList.pdf.toWord.description",
    href: "/pdf-tools/pdf-to-word",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "FileImage",
    label: "toolsList.pdf.toImages.label",
    description: "toolsList.pdf.toImages.description",
    href: "/pdf-tools/pdf-to-images",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "FileInput",
    label: "toolsList.pdf.fromImages.label",
    description: "toolsList.pdf.fromImages.description",
    href: "/pdf-tools/images-to-pdf",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "RotateCw",
    label: "toolsList.pdf.rotate.label",
    description: "toolsList.pdf.rotate.description",
    href: "/pdf-tools/rotate-pdf",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Lock",
    label: "toolsList.pdf.protect.label",
    description: "toolsList.pdf.protect.description",
    href: "/pdf-tools/protect-pdf",
    badge: "common.new",
    badgeColor: "bg-emerald-100 text-emerald-600",
  },
  {
    icon: "Unlock",
    label: "toolsList.pdf.unlock.label",
    description: "toolsList.pdf.unlock.description",
    href: "/pdf-tools/unlock-pdf",
    badge: null,
    badgeColor: "",
  },
];
