import { Tool } from "@/types/tools";

export const popularTools: Tool[] = [
  {
    icon: "Hash",
    label: "toolsList.text.wordCounter.label",
    description: "toolsList.text.wordCounter.description",
    href: "/text-tools/word-counter",
    badge: "common.popular",
    badgeColor: "bg-blue-100 text-blue-600",
  },
  {
    icon: "CaseSensitive",
    label: "toolsList.text.caseConverter.label",
    description: "toolsList.text.caseConverter.description",
    href: "/text-tools/case-converter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "AlignLeft",
    label: "toolsList.text.loremIpsum.label",
    description: "toolsList.text.loremIpsum.description",
    href: "/text-tools/lorem-ipsum",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Crop",
    label: "toolsList.image.resizer.label",
    description: "toolsList.image.resizer.description",
    href: "/image-tools/resizer",
    badge: "common.popular",
    badgeColor: "bg-violet-100 text-violet-600",
  },
  {
    icon: "Minimize2",
    label: "toolsList.image.compressor.label",
    description: "toolsList.image.compressor.description",
    href: "/image-tools/compressor",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "ImagePlus",
    label: "toolsList.image.converter.label",
    description: "toolsList.image.converter.description",
    href: "/image-tools/format-converter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "FilePlus2",
    label: "toolsList.pdf.merger.label",
    description: "toolsList.pdf.merger.description",
    href: "/pdf-tools/merger",
    badge: "common.popular",
    badgeColor: "bg-rose-100 text-rose-600",
  },
  {
    icon: "Scissors",
    label: "toolsList.pdf.splitter.label",
    description: "toolsList.pdf.splitter.description",
    href: "/pdf-tools/splitter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Minimize2",
    label: "toolsList.pdf.compressor.label",
    description: "toolsList.pdf.compressor.description",
    href: "/pdf-tools/compressor",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "FileJson",
    label: "toolsList.dev.jsonFormatter.label",
    description: "toolsList.dev.jsonFormatter.description",
    href: "/dev-tools/json-formatter",
    badge: "common.popular",
    badgeColor: "bg-emerald-100 text-emerald-600",
  },
  {
    icon: "Terminal",
    label: "toolsList.dev.regex.label",
    description: "toolsList.dev.regex.description",
    href: "/dev-tools/regex-tester",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Hash",
    label: "toolsList.dev.uuid.label",
    description: "toolsList.dev.uuid.description",
    href: "/dev-tools/uuid-generator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Ruler",
    label: "toolsList.math.unitConverter.label",
    description: "toolsList.math.unitConverter.description",
    href: "/math-tools/unit-converter",
    badge: "common.popular",
    badgeColor: "bg-amber-100 text-amber-600",
  },
  {
    icon: "Percent",
    label: "toolsList.math.percentage.label",
    description: "toolsList.math.percentage.description",
    href: "/math-tools/percentage-calculator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Binary",
    label: "toolsList.math.numberBase.label",
    description: "toolsList.math.numberBase.description",
    href: "/math-tools/number-base-converter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "KeyRound",
    label: "toolsList.security.passwordGenerator.label",
    description: "toolsList.security.passwordGenerator.description",
    href: "/security-tools/password-generator",
    badge: "common.popular",
    badgeColor: "bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-slate-300",
  },
  {
    icon: "Eye",
    label: "toolsList.security.passwordStrength.label",
    description: "toolsList.security.passwordStrength.description",
    href: "/security-tools/password-strength-checker",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "ShieldCheck",
    label: "toolsList.security.md5.label",
    description: "toolsList.security.md5.description",
    href: "/security-tools/md5-hash-generator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "LetterText",
    label: "toolsList.seo.metaGenerator.label",
    description: "toolsList.seo.metaGenerator.description",
    href: "/seo-tools/meta-generator",
    badge: "common.popular",
    badgeColor: "bg-sky-100 text-sky-600",
  },
  {
    icon: "Link",
    label: "toolsList.seo.slug.label",
    description: "toolsList.seo.slug.description",
    href: "/seo-tools/slug-generator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Hash",
    label: "toolsList.seo.keywordDensity.label",
    description: "toolsList.seo.keywordDensity.description",
    href: "/seo-tools/keyword-density-checker",
    badge: null,
    badgeColor: "",
  },
];
