import { Tool } from "@/types/tools";

export const seoTools: Tool[] = [
  {
    icon: "LetterText",
    label: "toolsList.seo.metaGenerator.label",
    description: "toolsList.seo.metaGenerator.description",
    href: "/seo-tools/meta-generator",
    badge: "common.popular",
    badgeColor: "bg-sky-100 text-sky-600",
  },
  {
    icon: "Link",
    label: "toolsList.seo.slug.label",
    description: "toolsList.seo.slug.description",
    href: "/seo-tools/slug-generator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Hash",
    label: "toolsList.seo.keywordDensity.label",
    description: "toolsList.seo.keywordDensity.description",
    href: "/seo-tools/keyword-density-checker",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "FileText",
    label: "toolsList.seo.robotsTxt.label",
    description: "toolsList.seo.robotsTxt.description",
    href: "/seo-tools/robots-generator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Map",
    label: "toolsList.seo.sitemap.label",
    description: "toolsList.seo.sitemap.description",
    href: "/seo-tools/sitemap-generator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Globe",
    label: "toolsList.seo.ogPreview.label",
    description: "toolsList.seo.ogPreview.description",
    href: "/seo-tools/og-previewer",
    badge: "common.new",
    badgeColor: "bg-emerald-100 text-emerald-600",
  },
  {
    icon: "AlignLeft",
    label: "toolsList.seo.readability.label",
    description: "toolsList.seo.readability.description",
    href: "/seo-tools/readability-checker",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Code2",
    label: "toolsList.seo.schema.label",
    description: "toolsList.seo.schema.description",
    href: "/seo-tools/schema-markup-generator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Search",
    label: "toolsList.seo.serpPreview.label",
    description: "toolsList.seo.serpPreview.description",
    href: "/seo-tools/serp-preview",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "BarChart2",
    label: "toolsList.seo.wordFrequency.label",
    description: "toolsList.seo.wordFrequency.description",
    href: "/seo-tools/word-frequency-counter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Link2",
    label: "toolsList.seo.canonical.label",
    description: "toolsList.seo.canonical.description",
    href: "/seo-tools/canonical-tag-generator",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Type",
    label: "toolsList.seo.characterCounter.label",
    description: "toolsList.seo.characterCounter.description",
    href: "/seo-tools/character-counter-seo",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "LayoutList",
    label: "toolsList.seo.headingAnalyzer.label",
    description: "toolsList.seo.headingAnalyzer.description",
    href: "/seo-tools/heading-structure-analyzer",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Languages",
    label: "toolsList.seo.hreflang.label",
    description: "toolsList.seo.hreflang.description",
    href: "/seo-tools/hreflang-generator",
    badge: null,
    badgeColor: "",
  },
];