import { Tool } from "@/types/tools";

export const textTools: Tool[] = [
  {
    icon: "Hash",
    label: "toolsList.text.wordCounter.label",
    description: "toolsList.text.wordCounter.description",
    href: "/text-tools/word-counter",
    badge: "common.popular",
    badgeColor: "bg-blue-100 text-blue-600",
  },
  {
    icon: "CaseSensitive",
    label: "toolsList.text.caseConverter.label",
    description: "toolsList.text.caseConverter.description",
    href: "/text-tools/case-converter",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "AlignLeft",
    label: "toolsList.text.loremIpsum.label",
    description: "toolsList.text.loremIpsum.description",
    href: "/text-tools/lorem-ipsum",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Scissors",
    label: "toolsList.text.diff.label",
    description: "toolsList.text.diff.description",
    href: "/text-tools/diff",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Search",
    label: "toolsList.text.findReplace.label",
    description: "toolsList.text.findReplace.description",
    href: "/text-tools/find-replace",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "Replace",
    label: "toolsList.text.repeater.label",
    description: "toolsList.text.repeater.description",
    href: "/text-tools/text-repeater",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "RemoveFormatting",
    label: "toolsList.text.removeFormatting.label",
    description: "toolsList.text.removeFormatting.description",
    href: "/text-tools/remove-formatting",
    badge: "common.new",
    badgeColor: "bg-emerald-100 text-emerald-600",
  },
  {
    icon: "WrapText",
    label: "toolsList.text.wrapper.label",
    description: "toolsList.text.wrapper.description",
    href: "/text-tools/text-wrapper",
    badge: null,
    badgeColor: "",
  },
  {
    icon: "LetterText",
    label: "toolsList.text.slugGenerator.label",
    description: "toolsList.text.slugGenerator.description",
    href: "/text-tools/slug-generator",
    badge: null,
    badgeColor: "",
  },
];
